# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  working-directory: 
    description: 'The directory of the caller'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
  os: 
    description: 'The operating system that ran your action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.working-directory }}