name: Docker Practice
on: push
jobs:
  caching:
    runs-on: ubuntu-latest
    name: Caching for Docker
    steps:
      - name: Cache docker images
        id: docker-cache
        uses: actions/cache@v1
        with:
          path: ~/
          key: docker1
      - name: Load docker from cache
        if: steps.cache.outputs.cache-hit == 'true'
        run: docker load --input ~/alpine.tar.gz
      - run: docker run -t alpine echo hello  
      - name: Save to cache if needed
        if: steps.cache.outputs.cache-hit != 'true'
        run: docker save --output ~/alpine.tar.gz alpine



