name: Docker Practice
on: push
jobs:
  caching:
    runs-on: ubuntu-latest
    name: Caching for Docker
    steps:
      - name: Cache docker images
        uses: actions/cache@v1
        with:
          path: /var/lib/docker
      - run: docker run -t alpine echo hello  



