name: Docker Practice
on: push
jobs:
  caching:
    runs-on: ubuntu-latest
    name: Caching for Docker
    steps:
      - name: Cache docker images
        uses: actions/cache@v1
        with:
          path: ~/docker
          key: docker
      - run: docker load --quiet --input ~/docker/alpine
      - run: docker run -t alpine echo hello  
      - run: docker save --quiet --output ~/docker/alpine



