name: Docker Practice
on: push
jobs:
  caching:
    runs-on: ubuntu-latest
    name: Caching for Docker
    env:
      DOCKER_IMAGE: alpine:3.10
    steps:
      - uses: actions/checkout@v1   
      - name: Cache setup for Docker
        id: docker-cache
        uses: actions/cache@v1
        with:
          path: ~/docker.tar.gz
          key: docker12
      - name: Save to cache if needed
        if: steps.docker-cache.outputs.cache-hit != 'true'
        run: |
          docker save --output ~/docker.tar.gz $DOCKER_IMAGE
          ls -l ~/
      - name: Load docker from cache
        run: |
          docker load --input  ~/docker.tar.gz
      - run: docker run -t $DOCKER_IMAGE echo hello  
      - name: Local docker action uses cache
        uses: ./ #uses alpine in the action's Dockerfile
      # enable to demonstrate external actions eager building
      # - name: External docker action should use cache
      #   uses: AutoModality/action-hello-world-docker@v1 




