name: Docker Practice
on: push
jobs:
  caching:
    runs-on: ubuntu-latest
    name: Caching for Docker
    steps:
      - name: Cache docker images
        uses: actions/cache@v1
        with:
          path: ~/
          key: docker
      - run: docker load --input ~/alpine
      - run: docker run -t alpine echo hello  
      - run: docker save --output ~/alpine alpine



