name: Docker Practice
on: push
jobs:
  caching:
    runs-on: ubuntu-latest
    name: Caching for Docker
    env:
      DOCKER_IMAGE: alpine:3.10
      DOCKER_VERSION: alpine@sha256:2171658620155679240babee0a7714f6509fae66898db422ad803b951257db78
      DOCKER_CACHE_DIR: ~/docker
    steps:
      - uses: actions/checkout@v1   
      - name: Cache setup for Docker
        id: docker-cache
        uses: actions/cache@v1
        with:
          path: ${{ env.DOCKER_CACHE_DIR }}
          key: docker-alpine-practice-1
      - name: Save to cache if needed
        if: steps.docker-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/docker
          docker pull $DOCKER_VERSION
          docker save --output ~/docker/docker.tar.gz $DOCKER_IMAGE
      - name: Load docker from cache
        run: |
          docker load --input  ~/docker/docker.tar.gz
      - run: docker run -t $DOCKER_IMAGE echo hello  
      - name: Local docker action uses cache
        uses: ./ #uses alpine in the action's Dockerfile
      # enable to demonstrate external actions eager building
      # - name: External docker action should use cache
      #   uses: AutoModality/action-hello-world-docker@v1 
  caching-script:
    runs-on: ubuntu-latest
    name: Script Caching for Docker
    env:
      DOCKER_CACHE_DIR: ~/docker
    steps:
      - uses: actions/checkout@v1   
      - name: Cache setup for Docker
        id: docker-cache
        uses: actions/cache@v1
        with:
          path: ${{ env.DOCKER_CACHE_DIR }}
          key: docker-alpine-script-practice-2
      - name: Setup Docker Image
        run: .github/docker-cache.sh $DOCKER_CACHE_DIR
      - run: docker run -t alpine echo hello  
      - name: Local docker action uses cache
        uses: ./ #uses alpine in the action's Dockerfile
      # enable to demonstrate external actions eager building
      # - name: External docker action should use cache
      #   uses: AutoModality/action-hello-world-docker@v1 




