name: Docker Practice
on: push
jobs:
  caching:
    runs-on: ubuntu-latest
    name: Caching for Docker
    env:
      DOCKER_IMAGE: alpine:3.10
      DOCKER_FILENAME: ~/docker-alpine-3.10.tar.gz
    steps:
      - uses: actions/checkout@v1   
      - name: Cache docker images
        id: docker-cache
        uses: actions/cache@v1
        with:
          path: ~/docker-alpine-3.10.tar.gz
          key: apline-1
      - name: Save to cache if needed
        if: steps.docker-cache.outputs.cache-hit != 'true'
        run: |
          echo filename = $DOCKER_FILENAME
          docker save --output $DOCKER_FILENAME $DOCKER_IMAGE
      - name: Load docker from cache
        run: |
          docker load --input $DOCKER_FILENAME
      - run: docker run -t $DOCKER_IMAGE echo hello  
      - name: Local docker action uses cache
        uses: ./ #uses alpine in the action's Dockerfile
      # enable to demonstrate external actions eager building
      # - name: External docker action should use cache
      #   uses: AutoModality/action-hello-world-docker@v1 




