name: Code Formatter
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: AutoModality/action-ros-clang-format@format-from-root
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

