name: Hello World Action
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: AutoModality/action-hello-world-docker@v1
      with:
        who-to-greet: 'AutoModality'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: Get the output os
      run: echo "The os was ${{ steps.hello.outputs.os }}"

