name: Repository Dispatch
on:
  repository_dispatch:
    types: [release]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: | 
          echo ${{ github.event.client_payload.sha }}
          echo ${{ github.event.client_payload.package }}
          echo ${{ github.event.client_payload.new_release_version }}
          echo ${{ github.event.client_payload.new_release_major_version }}
          echo ${{ github.event.client_payload.new_release_minor_version }}
          echo ${{ github.event.client_payload.new_release_patch_version }}
          echo ${{ github.event.client_payload.new_release_notes }}
          patch_version=${{ github.event.client_payload.new_release_patch_version }}
          minor_version=${{ github.event.client_payload.new_release_minor_version }}
          if [[ "$patch_version" == "0" ]]
          then
            if [[ "$minor_version" == "0" ]]
            then
              echo "Major Version"
            else
              echo "Minor Version"
          else
            echo "Patch Version"
