name: Release Candidate
on: 
  pull_request:
    branches:
      - master
jobs:
  release-candidate:
    runs-on: ubuntu-latest
    name: Release Candidate Demo
    steps:
    - name: Checkout
      uses: actions/checkout@v1      
    - name: Semantic Release
      id: semantic   # `id` for output variables
      uses: cycjimmy/semantic-release-action@master
      with:
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate build number
      if: steps.semantic.outputs.new_release_published == 'true'
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
    - name: Release Candidate Found
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        echo version ${{ steps.semantic.outputs.new_release_version }}-build.${{ steps.buildnumber.outputs.build_number }}





