name: Release and Deploy
on:
  - push
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Write release result to file
        run: |
          mkdir release
          echo ${{ steps.semantic.outputs.new_release_published }} > release/published.txt
      - name: Write version to file
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo ${{ steps.semantic.outputs.new_release_version }} > release/version.txt
      - name: Share release file with other jobs
        uses: actions/upload-artifact@v1
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          name: release
          path: release
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,ubuntu-16.04 ]
    needs: release
    name: Deploy if released
    steps:
      - name: Download release version, if available
        uses: actions/download-artifact@v1
        with:
          name: release
      - name: Deploy
        run: |
          published=$(cat release/published.txt)
          echo Release published: $published
          if [[ $published == true ]]; then 
            version=$(cat release/version.txt)
            echo "$version will be deployed"
          fi
