name: Release Race
on:
  - push
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delay the loser
        if: runner.os == 'Linux'
        run: sleep 60s
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,windows-2019 ]
    needs: release
    name: Demonstrates both systems may deploy after release
    steps:
      - name: Deploy
        if: jobs.release.steps.semantic.outputs.new_release_published == 'true'
        run: echo "${{ steps.semantic.outputs.new_release_version }} will be deployed"