name: Release Candidate
on: 
  pull_request:
    branches:
      - master
jobs:
  release-candidate:
    runs-on: ubuntu-latest
    name: Release Candidate Demo
    steps:
    - name: Checkout
      uses: actions/checkout@v1      
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        branch: ${{ steps.current.outputs.branch }}
        token: ${{secrets.github_token}}
    - name: Release Candidate Found
      run: |
        # {PR #}-{Issue Key}.{build number}
        echo version ${{ github.event.number }}.${{ github.event.pull_request.head.ref }}.${{ steps.buildnumber.outputs.build_number }}
    - name: Step that prints name of pull request's base branch
      if: github.event_name == 'pull_request'
      run: |
        echo "Pull request's base branch is: ${{ github.base_ref }}"
        echo "Pull request's head branch is: ${{ github.head_ref }}"




