name: Release Race
on:
  - push
jobs:
  realease-race:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,windows-2019 ]
    name: Demonstrates only one host will release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delay the loser
        if: runner.os == 'Linux'
        run: sleep 60s
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo "${{ steps.semantic.outputs.new_release_version }} will be deployed"
      - name: Release Versions
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo version ${{ steps.semantic.outputs.new_release_version }}
          echo major ${{ steps.semantic.outputs.new_release_major_version }}
          echo minor ${{ steps.semantic.outputs.new_release_minor_version }}
          echo patch ${{ steps.semantic.outputs.new_release_patch_version }}