name: Release Race
on:
  - push
jobs:
  realease-race:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,windows-2019 ]
    name: Demonstrates only one host will release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delay the loser
        if: runner.os == 'Linux'
        run: sleep 120s
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo "${{ steps.package.outputs.artifact-path }} will be deployed"

