name: Release Race
on:
  - push
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delay the loser
        if: runner.os == 'Linux'
        run: sleep 60s
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Write release to file
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo ${{ steps.semantic.outputs.new_release_version }} > release-version.txt
      - name: Share release file with other jobs
        uses: actions/upload-artifact@v1
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          name: release-version
          path: release-version.txt
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,windows-2019 ]
    needs: release
    name: Deploy if released
    steps:
      - name: Download release version, if available
        uses: actions/download-artifact@v1
        with:
          name: release-version
      - name: Deploy
        run: |
          version=$(cat release-version.txt)
          echo "${{ steps.semantic.outputs.new_release_version }} will be deployed"
